# Generated by Django 4.2.1 on 2023-06-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='date_of_import',
            field=models.DateField(blank=True, null=True),
        ),
    ]
