# Generated by Django 4.2.1 on 2023-06-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_order_date_order_date_of_import'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinstance',
            old_name='date_created',
            new_name='date_of_purchase',
        ),
    ]
