# Generated by Django 4.2.1 on 2023-06-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_stuff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stuff',
        ),
    ]
